name: 'ESP IDF SBOM Vulnerability Scan'
description: 'Scan manifest files with CPE info in repository for possible vulnerabilities'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  ref:
    description: 'Reference name. If not set `GITHUB_REF_NAME` is used by default.'
outputs:
  vulnerable:
    description: 'Set to 1 if vulnerability was found or 128 on error, 0 otherwise'
